### ISSUE TITLE
should add support for vagrant-gatling-rsync auto restart when crashed

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-essential#34]
when vagrant-gatling-rsync plugin is installed and this option `rsync_on_startup: true` is available

for example:

```
vagrant:
  plugins:
    - _id: "entry-gatling-rsync"
      name: vagrant-gatling-rsync
      version: "" # empty means latest by default
      state: installed
      enabled: true
      config_key: gatling
      options:
        latency: 0.5
        time_format: "%%H:%%M:%%S"
        rsync_on_startup: true
```

should work with multiple nodes
